---
layout: post
title: Tinix's different point of view.
comments: true


tags: [jekyll, disqus, ruby, rails, rust, go, elixir, programmings, Java, DevOps, FreeBSD , Linux, postgreSQL, MySQL,]
# Site settings
email: daniel.tinivella@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 Also known as Tinix , Degree in Computer Science FaMAF,Writer Software, Ruby, Elixir, Rust, Go, Linux and FreeBSD, I like have Mate, 4 lang​​, but all that means almost nothing..
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tinix.github.io" # the base hostname & protocol for your site
twitter_username: Tinix
github_username:  Tinix
gitlab_username:  Tinix



# Jekyll-Pagination
gems: [jekyll-paginate]
paginate: 5


# Build settings
markdown: kramdown

# Port
port: 3000

# Admin-Jekyll
jekyll_admin:
  hidden_links:
      #- posts
      #- pages
      #- staticfiles
      #- datafiles
      #    - configuration
